kind: Deployment
apiVersion: apps/v1
metadata:
  name: pinger
  labels:
    app: pinger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
      - name: pinger
        image: quay.io/marians/pinger:latest
      volumes:
      - name: config-volume
        configMap:
          name: pinger-config
          items:
          - key: config.yaml
            path: /config.yaml
